# Generated by Django 4.1.1 on 2023-12-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saunasession',
            name='avg_humid',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='saunasession',
            name='avg_pressure',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='saunasession',
            name='avg_temp',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='saunasession',
            name='blood_flow_increased',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='saunasession',
            name='calories_burned',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='saunasession',
            name='duration',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='saunasession',
            name='heartbit_increased',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reading',
            name='device',
            field=models.CharField(max_length=30),
        ),
    ]
