# Generated by Django 4.1.1 on 2024-05-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sauna", "0003_progression_fluttersession_badges"),
    ]

    operations = [
        migrations.AddField(
            model_name="fluttersession",
            name="feelings",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
