# Generated by Django 4.1.1 on 2023-10-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('site_name', models.CharField(max_length=100)),
                ('website_url', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='website/default.png', upload_to='website/')),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('short_desc', models.TextField(max_length=500)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('slug', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('thumbnail', models.ImageField(default='page/default.png', upload_to='page/')),
                ('video_url', models.CharField(blank=True, max_length=100, null=True)),
                ('page_type', models.IntegerField(choices=[(0, 'Privacy Policy'), (1, 'Terms and Condition'), (2, 'About Us'), (3, 'General')])),
                ('is_active', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
